CREATE TABLE data_science_edw.monthly_product_eligibility_snapshot (
    snapshot_start_dt date NOT NULL ENCODE az64,
    snapshot_end_dt date ENCODE az64,
    eligibility_reporting_dt date NOT NULL ENCODE az64,
    group_id integer NOT NULL ENCODE az64,
    group_nm character varying(1020) NOT NULL ENCODE lzo,
    group_type_cd character varying(160) ENCODE bytedict,
    service_specialty_cd character varying(1020) NOT NULL ENCODE bytedict,
    state_province_cd character varying(160) NOT NULL ENCODE lzo,
    state_province_nm character varying(1020) NOT NULL ENCODE lzo,
    report_category_nm character varying(1020) NOT NULL ENCODE lzo,
    report_category_value character varying(1020) NOT NULL ENCODE lzo,
    group_fee_type_cd character varying(160) ENCODE lzo,
    group_fee_type_nm character varying(1020) ENCODE lzo,
    primary_source_cd character varying(160) ENCODE bytedict,
    primary_source_nm character varying(1020) ENCODE bytedict,
    hierarchy_level integer ENCODE az64,
    zdel_org_tree_left_node integer ENCODE az64,
    zdel_org_tree_right_node integer ENCODE az64,
    organization_id integer NOT NULL ENCODE az64,
    organization_parent_id integer ENCODE az64,
    membership_itd_cnt integer NOT NULL ENCODE az64,
    pri_itd_cnt integer NOT NULL ENCODE az64,
    dep_itd_cnt integer NOT NULL ENCODE az64,
    eligible_lives_itd_cnt integer NOT NULL ENCODE az64,
    registered_membership_cnt integer NOT NULL ENCODE az64,
    registered_pri_cnt integer NOT NULL ENCODE az64,
    registered_dep_cnt integer NOT NULL ENCODE az64,
    ehr_completed_membership_cnt integer NOT NULL ENCODE az64,
    ehr_completed_pri_cnt integer NOT NULL ENCODE az64,
    ehr_completed_dep_cnt integer NOT NULL ENCODE az64,
    eligible_membership_incremental_cnt integer ENCODE az64,
    eligible_lives_pri_incremental_cnt integer ENCODE az64,
    eligible_lives_dep_incremental_cnt integer ENCODE az64,
    registered_membership_incremental_cnt integer NOT NULL ENCODE az64,
    registered_pri_incremental_cnt integer NOT NULL ENCODE az64,
    registered_dep_incremental_cnt integer NOT NULL ENCODE az64,
    ehr_completed_membership_incremental_cnt integer NOT NULL ENCODE az64,
    ehr_completed_pri_incremental_cnt integer NOT NULL ENCODE az64,
    ehr_completed_dep_incremental_cnt integer NOT NULL ENCODE az64,
    rte_count_current_month_flg character(1) ENCODE lzo,
    termination_membership_incremental_cnt integer ENCODE az64,
    termination_pri_incremental_cnt integer ENCODE az64,
    termination_dep_incremental_cnt integer ENCODE az64,
    new_welcome_kit_cnt integer ENCODE az64,
    reprint_welcome_kit_cnt integer ENCODE az64,
    retro_welcome_kit_cnt integer ENCODE az64,
    total_welcome_kit_cnt integer ENCODE az64,
    registration_request_call_center_pri_incremental_cnt integer ENCODE az64,
    registration_request_call_center_dep_incremental_cnt integer ENCODE az64,
    registration_request_call_center_pri_male_incremental_cnt integer ENCODE az64,
    registration_request_call_center_dep_male_incremental_cnt integer ENCODE az64,
    registration_request_call_center_pri_female_incremental_cnt integer ENCODE az64,
    registration_request_call_center_dep_female_incremental_cnt integer ENCODE az64,
    registration_request_call_center_pri_unknown_incremental_cnt integer ENCODE az64,
    registration_request_call_center_dep_unknown_incremental_cnt integer ENCODE az64,
    registration_request_call_center_pri_other_incremental_cnt integer ENCODE az64,
    registration_request_call_center_dep_other_incremental_cnt integer ENCODE az64,
    registration_request_admin_pri_incremental_cnt integer ENCODE az64,
    registration_request_admin_dep_incremental_cnt integer ENCODE az64,
    registration_request_admin_pri_male_incremental_cnt integer ENCODE az64,
    registration_request_admin_dep_male_incremental_cnt integer ENCODE az64,
    registration_request_admin_pri_female_incremental_cnt integer ENCODE az64,
    registration_request_admin_dep_female_incremental_cnt integer ENCODE az64,
    registration_request_admin_pri_unknown_incremental_cnt integer ENCODE az64,
    registration_request_admin_dep_unknown_incremental_cnt integer ENCODE az64,
    registration_request_admin_pri_other_incremental_cnt integer ENCODE az64,
    registration_request_admin_dep_other_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_pri_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_dep_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_pri_male_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_dep_male_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_pri_female_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_dep_female_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_pri_unknown_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_dep_unknown_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_pri_other_incremental_cnt integer ENCODE az64,
    registration_request_member_mobile_dep_other_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_pri_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_dep_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_pri_male_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_dep_male_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_pri_female_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_dep_female_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_pri_unknown_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_dep_unknown_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_pri_other_incremental_cnt integer ENCODE az64,
    registration_request_member_portal_dep_other_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_pri_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_dep_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_pri_male_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_dep_male_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_pri_female_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_dep_female_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_pri_unknown_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_dep_unknown_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_pri_other_incremental_cnt integer ENCODE az64,
    registration_request_partner_api_dep_other_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_pri_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_dep_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_pri_male_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_dep_male_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_pri_female_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_dep_female_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_pri_unknown_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_dep_unknown_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_pri_other_incremental_cnt integer ENCODE az64,
    registration_request_client_portal_dep_other_incremental_cnt integer ENCODE az64,
    registration_request_unknown_pri_incremental_cnt integer ENCODE az64,
    registration_request_unknown_dep_incremental_cnt integer ENCODE az64,
    source_nm character varying(240) NOT NULL ENCODE lzo,
    exclusion_cd character varying(160) NOT NULL ENCODE raw,
    exclusion_comment character varying(1020) ENCODE lzo,
    created_at timestamp without time zone NOT NULL ENCODE az64,
    created_by character varying(20) NOT NULL ENCODE lzo,
    updated_at timestamp without time zone NOT NULL ENCODE az64,
    updated_by character varying(20) NOT NULL ENCODE lzo,
    manual_update_id integer ENCODE az64,
    registration_request_mobilesdk_pri_incremental_cnt integer ENCODE az64,
    registration_request_mobilesdk_dep_incremental_cnt integer ENCODE az64,
    registration_request_mobilesdk_pri_male_incremental_cnt integer ENCODE az64,
    registration_request_mobilesdk_dep_male_incremental_cnt integer ENCODE az64,
    registration_request_mobilesdk_pri_female_incremental_cnt integer ENCODE az64,
    registration_request_mobilesdk_dep_female_incremental_cnt integer ENCODE az64,
    registration_request_mobilesdk_pri_unknown_incremental_cnt integer ENCODE az64,
    registration_request_mobilesdk_dep_unknown_incremental_cnt integer ENCODE az64,
    registration_request_mobilesdk_pri_other_incremental_cnt integer ENCODE az64,
    registration_request_mobilesdk_dep_other_incremental_cnt integer ENCODE az64,
    global_flg character(1) ENCODE lzo,
    member_country_cd character varying(160) NOT NULL ENCODE lzo,
    member_country_nm character varying(1020) NOT NULL ENCODE lzo,
    snapshot_year integer NOT NULL ENCODE az64,
    snapshot_year_month integer NOT NULL ENCODE az64,
    sql_path character varying(4000) ENCODE lzo,
    mbr_pay_cd character varying(160) ENCODE lzo,
    mbr_pay_lives_itd_cnt integer ENCODE az64,
    mbr_pay_lives_incr_cnt integer ENCODE az64,
    row_hash character varying(128) ENCODE lzo,
    key_hash character varying(128) ENCODE lzo,
    dep_below_18_itd_cnt integer ENCODE az64,
    dep_above_18_itd_cnt integer ENCODE az64,
    eligible_lives_above_18_itd_cnt integer ENCODE az64,
    registered_membership_excl_cncld_itd_cnt integer ENCODE az64,
    registered_pri_excl_cncld_itd_cnt integer ENCODE az64,
    registered_dep_excl_cncld_itd_cnt integer ENCODE az64,
    dep_below_18_incremental_cnt integer ENCODE az64,
    dep_above_18_incremental_cnt integer ENCODE az64,
    eligible_lives_above_18_incremental_cnt integer ENCODE az64,
    src_row_hash character varying(256) NOT NULL ENCODE lzo,
    tgt_row_hash character varying(256) NOT NULL ENCODE lzo,
    auto_id bigint ENCODE az64 distkey
)
DISTSTYLE KEY
SORTKEY ( exclusion_cd, exclusion_comment, report_category_nm, hierarchy_level, member_country_cd, group_id, organization_id, report_category_value );