CREATE TABLE data_sciences.nps_daily_responses (
    user_uuid character varying(36) NOT NULL ENCODE lzo distkey,
    month_first_enrolled_livongo date ENCODE az64,
    gender character varying(16) ENCODE lzo,
    race character varying(64) ENCODE lzo,
    race_hispanic character varying(16) ENCODE lzo,
    address_state character varying(3) ENCODE lzo,
    postal_code_nonpii character varying(10) ENCODE lzo,
    enrolled_any_program_current smallint NOT NULL ENCODE az64,
    programs_enrolled_at_response character varying(256) ENCODE lzo,
    age_at_response integer ENCODE az64,
    client_code_at_response character varying(64) ENCODE lzo,
    client_code_current character varying(64) ENCODE lzo,
    client_name_current character varying(256) ENCODE lzo,
    contract_paths_current character varying(256) ENCODE lzo,
    client_industry_current character varying(256) ENCODE lzo,
    client_type_current character varying(64) ENCODE lzo,
    client_success_manager_current character varying(256) ENCODE lzo,
    client_tier_current character varying(32) ENCODE lzo,
    client_status_current character varying(64) ENCODE lzo,
    client_segment_current character varying(255) ENCODE lzo,
    bob_contractual_exclusion integer ENCODE az64,
    client_launch_date date ENCODE az64,
    client_recruitment_began_date date ENCODE az64,
    tenure_sat_survey character varying(64) ENCODE lzo,
    response_time_utc timestamp without time zone ENCODE raw,
    response_month_start_utc date ENCODE az64,
    response_value smallint NOT NULL ENCODE mostly8,
    promoter smallint NOT NULL ENCODE mostly8,
    passive smallint NOT NULL ENCODE mostly8,
    detractor smallint NOT NULL ENCODE mostly8,
    nps_response_count smallint NOT NULL ENCODE mostly8,
    last_nps_response smallint NOT NULL ENCODE mostly8,
    race_name_list character varying(2000) ENCODE lzo,
    sr_race_eth_coarse character varying(38) ENCODE lzo,
    acjk character varying(5) ENCODE lzo,
    aian character varying(29) ENCODE lzo,
    baa character varying(22) ENCODE lzo,
    hlm character varying(16) ENCODE lzo,
    nhopi character varying(38) ENCODE lzo,
    o character varying(5) ENCODE lzo,
    wc character varying(5) ENCODE lzo
)
DISTSTYLE KEY
SORTKEY ( user_uuid, response_time_utc );