CREATE TABLE data_science_edw.monthly_consult_snapshot (
    auto_id integer NOT NULL ENCODE az64,
    key_hash character varying(240) NOT NULL ENCODE lzo,
    row_hash character varying(240) NOT NULL ENCODE lzo,
    snapshot_year integer NOT NULL ENCODE raw,
    snapshot_year_month integer NOT NULL ENCODE az64 distkey,
    snapshot_start_dt date NOT NULL ENCODE az64,
    snapshot_end_dt date ENCODE raw,
    group_id integer NOT NULL ENCODE az64,
    group_nm character varying(1020) NOT NULL ENCODE lzo,
    member_state_cd character varying(160) ENCODE lzo,
    member_state_nm character varying(1020) ENCODE lzo,
    consult_state_cd character varying(160) ENCODE bytedict,
    consult_state_nm character varying(1020) ENCODE bytedict,
    comm_method_cd character varying(160) ENCODE bytedict,
    service_specialty_cd character varying(160) ENCODE bytedict,
    provider_role_cd character varying(160) ENCODE bytedict,
    report_category_nm character varying(1020) NOT NULL ENCODE raw,
    report_category_value character varying(1020) ENCODE lzo,
    teladoc_emp_group_flg character(1) ENCODE lzo,
    hierarchy_level integer ENCODE az64,
    sql_path character varying(1020) ENCODE lzo,
    organization_id integer ENCODE az64,
    organization_parent_id integer ENCODE az64,
    total_consults integer ENCODE az64,
    video_consult_with_phone_audio integer ENCODE az64,
    video_consult_with_pc_audio integer ENCODE az64,
    consult_with_image_cnt integer ENCODE az64,
    consult_pri_cnt integer ENCODE az64,
    consult_dep_cnt integer ENCODE az64,
    callback_time_pri_cnt integer ENCODE az64,
    callback_time_dep_cnt integer ENCODE az64,
    satisfaction_outstanding_pri_cnt integer ENCODE az64,
    satisfaction_outstanding_dep_cnt integer ENCODE az64,
    satisfaction_good_pri_cnt integer ENCODE az64,
    satisfaction_good_dep_cnt integer ENCODE az64,
    satisfaction_poor_pri_cnt integer ENCODE az64,
    satisfaction_poor_dep_cnt integer ENCODE az64,
    total_rx_pri_cnt integer ENCODE az64,
    total_rx_dep_cnt integer ENCODE az64,
    consults_with_rx_pri_cnt integer ENCODE az64,
    consults_with_rx_dep_cnt integer ENCODE az64,
    scheduled_consult_pri_cnt integer ENCODE az64,
    scheduled_consult_dep_cnt integer ENCODE az64,
    ondemand_consult_pri_cnt integer ENCODE az64,
    ondemand_consult_dep_cnt integer ENCODE az64,
    consult_female_pri_cnt integer ENCODE az64,
    consult_female_dep_cnt integer ENCODE az64,
    consult_male_pri_cnt integer ENCODE az64,
    consult_male_dep_cnt integer ENCODE az64,
    consult_request_call_center_pri_cnt integer ENCODE az64,
    consult_request_call_center_dep_cnt integer ENCODE az64,
    consult_request_member_mobile_pri_cnt integer ENCODE az64,
    consult_request_member_mobile_dep_cnt integer ENCODE az64,
    consult_request_member_portal_pri_cnt integer ENCODE az64,
    consult_request_member_portal_dep_cnt integer ENCODE az64,
    consult_request_partner_api_pri_cnt integer ENCODE az64,
    consult_request_partner_api_dep_cnt integer ENCODE az64,
    callback_under_one_hour_pri_cnt integer ENCODE az64,
    callback_under_one_hour_dep_cnt integer ENCODE az64,
    callback_over_one_hour_pri_cnt integer ENCODE az64,
    callback_over_one_hour_dep_cnt integer ENCODE az64,
    paid_consults_cnt integer ENCODE az64,
    included_consults_cnt integer ENCODE az64,
    missed_sla_cnt integer ENCODE az64,
    customer_service_cnt integer ENCODE az64,
    promotional_marketing_cnt integer ENCODE az64,
    missing_invoice_cnt integer ENCODE az64,
    consult_request_pri_cnt integer ENCODE az64,
    consult_request_dep_cnt integer ENCODE az64,
    consult_cancel_pri_cnt integer ENCODE az64,
    consult_cancel_dep_cnt integer ENCODE az64,
    scheduled_to_actual_start_under_5_min_pri_cnt integer ENCODE az64,
    scheduled_to_actual_start_under_5_min_dep_cnt integer ENCODE az64,
    scheduled_to_actual_start_5_to_10_min_pri_cnt integer ENCODE az64,
    scheduled_to_actual_start_5_to_10_min_dep_cnt integer ENCODE az64,
    scheduled_to_actual_start_over_10_min_pri_cnt integer ENCODE az64,
    scheduled_to_actual_start_over_10_min_dep_cnt integer ENCODE az64,
    negotiation_request_to_provider_response_under_24_hour_pri_cnt integer ENCODE az64,
    negotiation_request_to_provider_response_under_24_hour_dep_cnt integer ENCODE az64,
    negotiation_request_to_provider_response_24_to_48_hour_pri_cnt integer ENCODE az64,
    negotiation_request_to_provider_response_24_to_48_hour_dep_cnt integer ENCODE az64,
    negotiation_request_to_provider_response_over_48_hour_pri_cnt integer ENCODE az64,
    negotiation_request_to_provider_response_over_48_hour_dep_cnt integer ENCODE az64,
    end_to_end_time_under_7_day_pri_cnt integer ENCODE az64,
    end_to_end_time_under_7_day_dep_cnt integer ENCODE az64,
    end_to_end_time_7_to_14_day_pri_cnt integer ENCODE az64,
    end_to_end_time_7_to_14_day_dep_cnt integer ENCODE az64,
    end_to_end_time_over_14_day_pri_cnt integer ENCODE az64,
    end_to_end_time_over_14_day_dep_cnt integer ENCODE az64,
    would_use_service_again_yes_pri_cnt integer ENCODE az64,
    would_use_service_again_yes_dep_cnt integer ENCODE az64,
    would_use_service_again_no_pri_cnt integer ENCODE az64,
    would_use_service_again_no_dep_cnt integer ENCODE az64,
    would_use_service_again_dont_know_pri_cnt integer ENCODE az64,
    would_use_service_again_dont_know_dep_cnt integer ENCODE az64,
    is_blank_flg character(1) ENCODE lzo,
    source_system_nm character varying(240) ENCODE lzo,
    source_system_consult_pri integer ENCODE az64,
    source_system_consult_dep integer ENCODE az64,
    source_system_total_consult_cnt integer ENCODE az64,
    source_system_consult_pri_ytd_cnt integer ENCODE az64,
    source_system_consult_dep_ytd_cnt integer ENCODE az64,
    source_system_total_consult_ytd_cnt integer ENCODE az64,
    source_nm character varying(240) NOT NULL ENCODE lzo,
    exclusion_cd character varying(160) NOT NULL ENCODE raw,
    exclusion_comment character varying(1020) ENCODE lzo,
    global_flg character(10) ENCODE lzo,
    member_country_cd character varying(160) ENCODE lzo,
    member_country_nm character varying(1020) ENCODE bytedict,
    consult_country_cd character varying(160) ENCODE lzo,
    consult_country_nm character varying(1020) ENCODE bytedict,
    initial_session_cnt integer NOT NULL ENCODE az64,
    ongoing_session_cnt integer NOT NULL ENCODE az64,
    upcoming_session_cnt integer NOT NULL ENCODE az64,
    on_demand_any_provider_cnt integer NOT NULL ENCODE az64,
    scheduled_any_provider_cnt integer NOT NULL ENCODE az64,
    on_demand_select_provider_cnt integer NOT NULL ENCODE az64,
    scheduled_select_provider_cnt integer NOT NULL ENCODE az64,
    wait_time_on_demand_any_provider_mins_sum numeric(7,2) NOT NULL ENCODE az64,
    wait_time_scheduled_any_provider_mins_sum numeric(7,2) NOT NULL ENCODE az64,
    wait_time_on_demand_select_provider_mins_sum numeric(7,2) NOT NULL ENCODE az64,
    wait_time_scheduled_select_provider_mins_sum numeric(7,2) NOT NULL ENCODE az64,
    consult_request_member_mobile_sdk_pri_cnt integer NOT NULL ENCODE az64,
    consult_request_member_mobile_sdk_dep_cnt integer NOT NULL ENCODE az64,
    created_at timestamp without time zone NOT NULL ENCODE az64,
    created_by character varying(20) NOT NULL ENCODE lzo,
    updated_at timestamp without time zone NOT NULL ENCODE az64,
    updated_by character varying(20) NOT NULL ENCODE lzo,
    src_row_hash character varying(256) NOT NULL ENCODE lzo,
    tgt_row_hash character varying(256) NOT NULL ENCODE lzo,
    visit_resp_time_seconds_sum bigint ENCODE az64,
    visit_time_to_completion_seconds_sum bigint ENCODE az64,
    visit_resp_time_under_one_hr_cnt integer ENCODE az64,
    PRIMARY KEY (auto_id, snapshot_year_month)
)
DISTSTYLE KEY
SORTKEY ( exclusion_cd, global_flg, report_category_nm, comm_method_cd, source_nm, provider_role_cd, snapshot_year, service_specialty_cd, consult_state_cd, snapshot_start_dt, snapshot_end_dt, snapshot_year_month, member_state_cd, group_id, group_nm, organization_id, report_category_value, row_hash, key_hash, auto_id );