CREATE TABLE nonpii.member_daily_summary (
    date_utc date NOT NULL ENCODE runlength,
    user_id bigint NOT NULL ENCODE raw distkey,
    client_code character varying(50) NOT NULL ENCODE text32k,
    shipped_bg_meters_welcome smallint NOT NULL ENCODE mostly8,
    shipped_bg_meters_replacement smallint NOT NULL ENCODE mostly8,
    shipped_bg_strip_units smallint NOT NULL ENCODE mostly8,
    shipped_bg_strip_units_30day smallint NOT NULL ENCODE mostly8,
    shipped_bg_lancet_units smallint NOT NULL ENCODE mostly8,
    shipped_bg_lancing_devices smallint NOT NULL ENCODE mostly8,
    shipped_bg_control_solutions smallint NOT NULL ENCODE mostly8,
    shipped_htn_monitors_welcome smallint NOT NULL ENCODE mostly8,
    shipped_htn_monitors_replacement smallint NOT NULL ENCODE mostly8,
    shipped_scales_welcome smallint NOT NULL ENCODE mostly8,
    shipped_scales_replacement smallint NOT NULL ENCODE mostly8,
    returned_bg_meters_welcome smallint NOT NULL ENCODE mostly8,
    returned_bg_meters_replacement smallint NOT NULL ENCODE mostly8,
    returned_bg_strip_units smallint NOT NULL ENCODE mostly8,
    returned_bg_lancet_units smallint NOT NULL ENCODE mostly8,
    returned_bg_lancing_devices smallint NOT NULL ENCODE mostly8,
    returned_bg_control_solutions smallint NOT NULL ENCODE mostly8,
    returned_htn_monitors_welcome smallint NOT NULL ENCODE mostly8,
    returned_htn_monitors_replacement smallint NOT NULL ENCODE mostly8,
    returned_scales_welcome smallint NOT NULL ENCODE mostly8,
    returned_scales_replacement smallint NOT NULL ENCODE mostly8,
    bg_check_count smallint NOT NULL ENCODE mostly8,
    bg_check_count_7day smallint NOT NULL ENCODE mostly8,
    bg_check_count_30day smallint NOT NULL ENCODE mostly8,
    bg_check_count_90day smallint NOT NULL ENCODE mostly8,
    bg_checked smallint NOT NULL ENCODE mostly8,
    bg_checked_7day smallint NOT NULL ENCODE mostly8,
    bg_checked_30day smallint NOT NULL ENCODE mostly8,
    bg_checked_90day smallint NOT NULL ENCODE mostly8,
    bg_hypo_count smallint NOT NULL ENCODE mostly8,
    bg_hypo_count_7day smallint NOT NULL ENCODE mostly8,
    bg_hypo_count_30day smallint NOT NULL ENCODE mostly8,
    bg_hypo_count_90day smallint NOT NULL ENCODE mostly8,
    bg_hyper_count smallint NOT NULL ENCODE mostly8,
    bg_hyper_count_7day smallint NOT NULL ENCODE mostly8,
    bg_hyper_count_30day smallint NOT NULL ENCODE mostly8,
    bg_hyper_count_90day smallint NOT NULL ENCODE mostly8,
    bg_avg_7day real ENCODE raw,
    bg_avg_30day real ENCODE raw,
    bg_avg_90day real ENCODE raw,
    bg_nathan_a1c_7day real ENCODE raw,
    bg_nathan_a1c_30day real ENCODE raw,
    bg_nathan_a1c_90day real ENCODE raw,
    bg_observable smallint ENCODE az64,
    bg_observable_30day smallint ENCODE az64,
    bg_observable_90day smallint ENCODE az64,
    bg_strip_errors smallint NOT NULL ENCODE mostly8,
    bg_strip_errors_7day smallint NOT NULL ENCODE mostly8,
    bg_strip_errors_30day smallint NOT NULL ENCODE mostly8,
    bp_readings smallint NOT NULL ENCODE mostly8,
    bp_readings_7day smallint NOT NULL ENCODE mostly8,
    bp_readings_30day smallint NOT NULL ENCODE mostly8,
    bp_readings_systolic_above_range smallint NOT NULL ENCODE mostly8,
    bp_readings_systolic_above_range_30day smallint NOT NULL ENCODE mostly8,
    bp_readings_systolic_above_range_90day smallint NOT NULL ENCODE mostly8,
    bp_readings_systolic_in_range smallint NOT NULL ENCODE mostly8,
    bp_readings_systolic_in_range_30day smallint NOT NULL ENCODE mostly8,
    bp_readings_systolic_in_range_90day smallint NOT NULL ENCODE mostly8,
    bp_avg_systolic_30day real ENCODE raw,
    bp_avg_systolic_90day real ENCODE raw,
    weights smallint NOT NULL ENCODE mostly8,
    weights_7day smallint NOT NULL ENCODE mostly8,
    weights_30day smallint NOT NULL ENCODE mostly8,
    weights_90day smallint NOT NULL ENCODE mostly8,
    weight_checked smallint NOT NULL ENCODE mostly8,
    weight_checked_7day smallint NOT NULL ENCODE mostly8,
    weight_checked_30day smallint NOT NULL ENCODE mostly8,
    weight_checked_90day smallint NOT NULL ENCODE mostly8,
    weight_avg_7day real ENCODE raw,
    weight_avg_30day real ENCODE raw,
    weight_avg_90day real ENCODE raw,
    activity_last_date_bg_check date ENCODE delta,
    activity_last_date_bp_reading date ENCODE delta,
    activity_last_date_weight date ENCODE delta,
    activity_last_date_coaching date ENCODE delta,
    activity_last_date_web date ENCODE delta,
    activity_last_date_mobile date ENCODE delta,
    activity_last_date_supplies_shipped date ENCODE delta,
    activity_last_date_any date ENCODE delta,
    activity_any smallint NOT NULL ENCODE mostly8,
    activity_any_7day smallint NOT NULL ENCODE mostly8,
    activity_any_30day smallint NOT NULL ENCODE mostly8,
    activity_any_90day smallint NOT NULL ENCODE mostly8,
    activity_last_bg_check_time_utc timestamp without time zone ENCODE az64,
    account_deactivation_date date ENCODE az64,
    account_status character varying(32) ENCODE lzo,
    active_min smallint NOT NULL DEFAULT 0 ENCODE mostly8,
    active_min_7day smallint NOT NULL DEFAULT 0 ENCODE mostly8,
    active_min_30day integer NOT NULL DEFAULT 0 ENCODE az64,
    active_min_90day integer NOT NULL DEFAULT 0 ENCODE az64,
    bh_activity_count integer ENCODE az64,
    bh_activity_count_7day integer ENCODE az64,
    bh_activity_count_30day integer ENCODE az64,
    bh_activity_count_90day integer ENCODE az64,
    bh_activity_last_date_app_session date ENCODE az64,
    bh_activity_last_coaching_engaged date ENCODE az64,
    activity_last_date_bh_activity_completed date ENCODE az64,
    bp_avg_diastolic_30day real ENCODE raw,
    food_log_submission_count_7day smallint ENCODE az64,
    food_log_submission_count_30day smallint ENCODE az64,
    hcsc_activity_count smallint NOT NULL DEFAULT 0 ENCODE mostly8,
    account_deactivation_reason character varying(32) ENCODE lzo,
    activity_any_active date ENCODE delta,
    activity_most_active date ENCODE delta,
    activity_last_date_teams date ENCODE delta
)
DISTSTYLE KEY
SORTKEY ( date_utc, user_id, client_code );